// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.6
// source: car_position.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarId int64 `protobuf:"varint,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

type Coords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xcoord int64 `protobuf:"varint,1,opt,name=xcoord,proto3" json:"xcoord,omitempty"`
	Ycoord int64 `protobuf:"varint,2,opt,name=ycoord,proto3" json:"ycoord,omitempty"`
}

func (x *Coords) Reset() {
	*x = Coords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coords) ProtoMessage() {}

func (x *Coords) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coords.ProtoReflect.Descriptor instead.
func (*Coords) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{1}
}

func (x *Coords) GetXcoord() int64 {
	if x != nil {
		return x.Xcoord
	}
	return 0
}

func (x *Coords) GetYcoord() int64 {
	if x != nil {
		return x.Ycoord
	}
	return 0
}

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *Id     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Point *Coords `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{2}
}

func (x *Car) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Car) GetPoint() *Coords {
	if x != nil {
		return x.Point
	}
	return nil
}

type Circle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *Coords `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Area  float32 `protobuf:"fixed32,2,opt,name=area,proto3" json:"area,omitempty"`
}

func (x *Circle) Reset() {
	*x = Circle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{3}
}

func (x *Circle) GetPoint() *Coords {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *Circle) GetArea() float32 {
	if x != nil {
		return x.Area
	}
	return 0
}

type Cars struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars []*Car `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
}

func (x *Cars) Reset() {
	*x = Cars{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cars) ProtoMessage() {}

func (x *Cars) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cars.ProtoReflect.Descriptor instead.
func (*Cars) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{4}
}

func (x *Cars) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_position_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_car_position_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_car_position_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_car_position_proto protoreflect.FileDescriptor

var file_car_position_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1b, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x72, 0x49, 0x64, 0x22, 0x38,
	0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x78, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x78, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x79, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x79, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x22, 0x51, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12,
	0x1f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61,
	0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x73, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x06, 0x43,
	0x69, 0x72, 0x63, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x22, 0x2c, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0xaa, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x2e,
	0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x1a,
	0x13, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x12, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x4e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x73, 0x12, 0x13, 0x2e, 0x63, 0x61, 0x72, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x1a, 0x11, 0x2e, 0x63,
	0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x73, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_car_position_proto_rawDescOnce sync.Once
	file_car_position_proto_rawDescData = file_car_position_proto_rawDesc
)

func file_car_position_proto_rawDescGZIP() []byte {
	file_car_position_proto_rawDescOnce.Do(func() {
		file_car_position_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_position_proto_rawDescData)
	})
	return file_car_position_proto_rawDescData
}

var file_car_position_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_car_position_proto_goTypes = []interface{}{
	(*Id)(nil),     // 0: carPosition.Id
	(*Coords)(nil), // 1: carPosition.Coords
	(*Car)(nil),    // 2: carPosition.Car
	(*Circle)(nil), // 3: carPosition.Circle
	(*Cars)(nil),   // 4: carPosition.Cars
	(*Status)(nil), // 5: carPosition.Status
}
var file_car_position_proto_depIdxs = []int32{
	0, // 0: carPosition.Car.id:type_name -> carPosition.Id
	1, // 1: carPosition.Car.point:type_name -> carPosition.Coords
	1, // 2: carPosition.Circle.point:type_name -> carPosition.Coords
	2, // 3: carPosition.Cars.cars:type_name -> carPosition.Car
	2, // 4: carPosition.CarPosition.Store:input_type -> carPosition.Car
	0, // 5: carPosition.CarPosition.Retrieve:input_type -> carPosition.Id
	3, // 6: carPosition.CarPosition.Neighbors:input_type -> carPosition.Circle
	5, // 7: carPosition.CarPosition.Store:output_type -> carPosition.Status
	1, // 8: carPosition.CarPosition.Retrieve:output_type -> carPosition.Coords
	4, // 9: carPosition.CarPosition.Neighbors:output_type -> carPosition.Cars
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_car_position_proto_init() }
func file_car_position_proto_init() {
	if File_car_position_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_car_position_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_position_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_position_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_position_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Circle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_position_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cars); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_position_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_position_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_position_proto_goTypes,
		DependencyIndexes: file_car_position_proto_depIdxs,
		MessageInfos:      file_car_position_proto_msgTypes,
	}.Build()
	File_car_position_proto = out.File
	file_car_position_proto_rawDesc = nil
	file_car_position_proto_goTypes = nil
	file_car_position_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarPositionClient is the client API for CarPosition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarPositionClient interface {
	Store(ctx context.Context, in *Car, opts ...grpc.CallOption) (*Status, error)
	Retrieve(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Coords, error)
	Neighbors(ctx context.Context, in *Circle, opts ...grpc.CallOption) (*Cars, error)
}

type carPositionClient struct {
	cc grpc.ClientConnInterface
}

func NewCarPositionClient(cc grpc.ClientConnInterface) CarPositionClient {
	return &carPositionClient{cc}
}

func (c *carPositionClient) Store(ctx context.Context, in *Car, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/carPosition.CarPosition/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carPositionClient) Retrieve(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Coords, error) {
	out := new(Coords)
	err := c.cc.Invoke(ctx, "/carPosition.CarPosition/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carPositionClient) Neighbors(ctx context.Context, in *Circle, opts ...grpc.CallOption) (*Cars, error) {
	out := new(Cars)
	err := c.cc.Invoke(ctx, "/carPosition.CarPosition/Neighbors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarPositionServer is the server API for CarPosition service.
type CarPositionServer interface {
	Store(context.Context, *Car) (*Status, error)
	Retrieve(context.Context, *Id) (*Coords, error)
	Neighbors(context.Context, *Circle) (*Cars, error)
}

// UnimplementedCarPositionServer can be embedded to have forward compatible implementations.
type UnimplementedCarPositionServer struct {
}

func (*UnimplementedCarPositionServer) Store(context.Context, *Car) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedCarPositionServer) Retrieve(context.Context, *Id) (*Coords, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (*UnimplementedCarPositionServer) Neighbors(context.Context, *Circle) (*Cars, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Neighbors not implemented")
}

func RegisterCarPositionServer(s *grpc.Server, srv CarPositionServer) {
	s.RegisterService(&_CarPosition_serviceDesc, srv)
}

func _CarPosition_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Car)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPositionServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/carPosition.CarPosition/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPositionServer).Store(ctx, req.(*Car))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarPosition_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPositionServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/carPosition.CarPosition/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPositionServer).Retrieve(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarPosition_Neighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Circle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarPositionServer).Neighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/carPosition.CarPosition/Neighbors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarPositionServer).Neighbors(ctx, req.(*Circle))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarPosition_serviceDesc = grpc.ServiceDesc{
	ServiceName: "carPosition.CarPosition",
	HandlerType: (*CarPositionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _CarPosition_Store_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _CarPosition_Retrieve_Handler,
		},
		{
			MethodName: "Neighbors",
			Handler:    _CarPosition_Neighbors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car_position.proto",
}
